export const DOCTOR_DEPARTMENTS = [
	"General Medicine",
	"Family Medicine",
	"Internal Medicine",
	"Emergency Medicine",
	"Critical Care Medicine",
	"Anesthesiology",
	"Cardiology",
	"Interventional Cardiology",
	"Cardiothoracic Surgery",
	"Neurology",
	"Neurosurgery",
	"Psychiatry",
	"Clinical Psychology",
	"Dermatology",
	"Endocrinology",
	"Diabetology",
	"Gastroenterology",
	"Hepatology",
	"Nephrology",
	"Urology",
	"Pulmonology",
	"Rheumatology",
	"Hematology",
	"Oncology",
	"Radiation Oncology",
	"Medical Oncology",
	"Surgical Oncology",
	"Orthopedics",
	"Spine Surgery",
	"Trauma Surgery",
	"General Surgery",
	"Plastic and Reconstructive Surgery",
	"Pediatric Surgery",
	"Vascular Surgery",
	"Ophthalmology",
	"ENT",
	"Dentistry",
	"Oral and Maxillofacial Surgery",
	"Obstetrics and Gynecology",
	"Reproductive Endocrinology and Infertility",
	"Pediatrics",
	"Neonatology",
	"Geriatrics",
	"Infectious Disease",
	"Allergy and Immunology",
	"Physical Medicine and Rehabilitation",
	"Sports Medicine",
	"Palliative Care",
	"Pain Medicine",
	"Nuclear Medicine",
	"Radiology",
	"Interventional Radiology",
	"Pathology",
	"Forensic Medicine",
	"Public Health",
	"Occupational Medicine",
	"Aviation Medicine",
	"Hyperbaric Medicine",
	"Sleep Medicine",
	"Clinical Pharmacology",
	"Veterinary General Practice",
	"Veterinary Internal Medicine",
	"Veterinary Surgery",
	"Veterinary Emergency and Critical Care",
	"Veterinary Cardiology",
	"Veterinary Neurology",
	"Veterinary Oncology",
	"Veterinary Dermatology",
	"Veterinary Ophthalmology",
	"Veterinary Dentistry",
	"Veterinary Anesthesiology",
	"Veterinary Diagnostic Imaging",
	"Veterinary Pathology",
	"Veterinary Public Health",
	"Veterinary Epidemiology",
	"Veterinary Parasitology",
	"Veterinary Microbiology",
	"Veterinary Theriogenology",
	"Veterinary Orthopedics",
	"Veterinary Behavior Medicine",
	"Avian Medicine",
	"Exotic Animal Medicine",
	"Zoo and Wildlife Medicine",
	"Aquatic Animal Medicine",
	"Equine Medicine",
	"Large Animal Medicine",
	"Small Animal Medicine",
] as const;

export type DoctorDepartment = (typeof DOCTOR_DEPARTMENTS)[number];
