export const DHAKA_AREAS = [
	"Adabor",
	"Agargaon",
	"Badda",
	"Banani",
	"Baridhara",
	"Bashabo",
	"Bashundhara",
	"Cantonment",
	"Dakshinkhan",
	"Demra",
	"Dhanmondi",
	"Farmgate",
	"Gendaria",
	"Gulshan",
	"Hazaribagh",
	"Jatrabari",
	"Kafrul",
	"Kalabagan",
	"Khilgaon",
	"Khilkhet",
	"Lalbagh",
	"Lalmatia",
	"Mirpur",
	"Mohakhali",
	"Mohammadpur",
	"Motijheel",
	"Mugda",
	"Old Dhaka",
	"Pallabi",
	"Rayer Bazar",
	"Rupnagar",
	"Shyamoli",
	"Tejgaon",
	"Uttara",
	"Wari",
] as const;

export const RATING_OPTIONS = [
	{ label: "4.5+ Stars", value: "4.5" },
	{ label: "4.0+ Stars", value: "4.0" },
	{ label: "3.5+ Stars", value: "3.5" },
] as const;

export const DEFAULT_PAGE_SIZE = 10;
