export const HOSPITAL_TYPES = [
	"General Hospital",
	"Multi-Specialty Hospital",
	"Super-Specialty Hospital",
	"Teaching Hospital",
	"University Hospital",
	"Research Hospital",
	"Community Hospital",
	"District Hospital",
	"Rural Hospital",
	"Urban Hospital",
	"Government Hospital",
	"Private Hospital",
	"Military Hospital",
	"Police Hospital",
	"Charity Hospital",
	"Faith-Based Hospital",
	"Children's Hospital",
	"Women's Hospital",
	"Maternity Hospital",
	"Geriatric Hospital",
	"Trauma Center",
	"Emergency Hospital",
	"Rehabilitation Hospital",
	"Psychiatric Hospital",
	"Mental Health Hospital",
	"Addiction Treatment Hospital",
	"Oncology Hospital",
	"Cardiology Hospital",
	"Cardiothoracic Hospital",
	"Neurology Hospital",
	"Neurosurgery Hospital",
	"Orthopedic Hospital",
	"Spine Hospital",
	"Kidney Specialist Hospital",
	"Urology Hospital",
	"Nephrology Hospital",
	"Liver Hospital",
	"Gastroenterology Hospital",
	"Pulmonology Hospital",
	"Respiratory Hospital",
	"Endocrinology Hospital",
	"Diabetes Hospital",
	"Hematology Hospital",
	"Infectious Disease Hospital",
	"Dermatology Hospital",
	"ENT Hospital",
	"Eye Hospital",
	"Ophthalmology Hospital",
	"Dental Hospital",
	"Oral and Maxillofacial Hospital",
	"Plastic Surgery Hospital",
	"Burn Hospital",
	"Obstetrics and Gynecology Hospital",
	"Fertility Hospital",
	"Pediatric Hospital",
	"Neonatal Hospital",
	"Sports Medicine Hospital",
	"Palliative Care Hospital",
	"Hospice Hospital",
	"Tuberculosis Hospital",
	"Leprosy Hospital",
	"Cancer Institute Hospital",
	"Heart Institute Hospital",
	"Transplant Hospital",
	"Veterinary Hospital",
	"Animal Specialty Hospital",
	"Exotic Animal Hospital",
	"Equine Hospital",
	"Wildlife Hospital",
] as const;

export type HospitalType = (typeof HOSPITAL_TYPES)[number];

export const ANIMAL_TYPES = [
	"Veterinary Hospital",
	"Animal Specialty Hospital",
	"Exotic Animal Hospital",
	"Equine Hospital",
	"Wildlife Hospital",
] as const satisfies HospitalType[];
