import { Doctor } from "@/models";
import mongoose from "mongoose";  // adjust path if needed

const IBN_SINA_DHANMONDI_ID = "6a3b995bb8b56320358b0efa"; // New ID for Ibn Sina


const doctorsSeed = [
	{
		name: "Professor Dr. Md. Ayub Ali Chowdhury",
		slug: "professor-dr-md-ayub-ali-chowdhury",
		departments: ["Internal Medicine", "Nephrology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1985 },
			{ degree: "FCPS (Medicine)", institution: "BCPS", passingYear: 1992 },
			{ degree: "MD (Nephrology)", institution: "NIKDU", passingYear: 1998 },
		],
		designation: "Professor",
		experience: 38,
		bio: "Professor at NIKDU (Rtd.) and Gold Medalist specializing in Kidney diseases and Internal Medicine.",
		contact: { phone: "+88 09610010615", email: "ayub.ali@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-001",
		speciality: ["Medicine", "Kidney Disease"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.9,
		reviewCount: 310,
	},
	{
		name: "Prof. Dr. M.A Baqui",
		slug: "prof-dr-m-a-baqui",
		departments: ["Cardiology", "Interventional Cardiology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1988 },
			{ degree: "D-Card(DU)", institution: "Dhaka University", passingYear: 1995 },
			{ degree: "FACC", institution: "America", passingYear: 2005 },
		],
		designation: "Professor",
		experience: 35,
		bio: "Clinical & Interventional Cardiology expert, formerly at NICVD.",
		contact: { phone: "+88 09610010615", email: "ma.baqui@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-002",
		speciality: ["Clinical Cardiology", "Interventional Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 220,
	},
	{
		name: "Prof. Dr. Khondker Shaheed Hussain",
		slug: "prof-dr-khondker-shaheed-hussain",
		departments: ["Cardiology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1987 },
			{ degree: "MD (Cardiology)", institution: "NICVD", passingYear: 1996 },
		],
		designation: "Professor",
		experience: 36,
		bio: "Specialist in Clinical & Interventional Cardiology, ex-NICVD.",
		contact: { phone: "+88 09610010615", email: "ks.hussain@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-003",
		speciality: ["Clinical & Interventional Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.7,
		reviewCount: 185,
	},
	{
		name: "DR. MD. MESBAHUL ISLAM",
		slug: "dr-md-mesbahul-islam",
		departments: ["Cardiology", "Interventional Cardiology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1998 },
			{ degree: "DCard", institution: "", passingYear: 2005 },
			{ degree: "MD (Cardiology)", institution: "", passingYear: 2012 },
		],
		designation: "Assistant Professor",
		experience: 25,
		bio: "Interventional Cardiologist focused on modern cardiac procedures.",
		contact: { phone: "+88 09610010615", email: "mesbahul.islam@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-004",
		speciality: ["Interventional Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.6,
		reviewCount: 110,
	},
	{
		name: "DR. A.T.M Nurannabi Shah",
		slug: "dr-a-t-m-nurannabi-shah",
		departments: ["Cardiology"],
		qualifications: [
			{ degree: "MBBS(DMC)", institution: "DMC", passingYear: 2000 },
			{ degree: "C. Card", institution: "NICVD", passingYear: 2007 },
			{ degree: "FRSH(London)", institution: "London", passingYear: 2010 },
		],
		designation: "Assistant Professor",
		experience: 23,
		bio: "Cardiology specialist and WHO Fellow (India) at NICVD.",
		contact: { phone: "+88 09610010615", email: "nurannabi.shah@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-005",
		speciality: ["Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.5,
		reviewCount: 88,
	},
	{
		name: "Dr. Sufia Jannat",
		slug: "dr-sufia-jannat",
		departments: ["Cardiology", "Internal Medicine", "Diabetology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 2002 },
			{ degree: "FCPS(Medicine)", institution: "BCPS", passingYear: 2010 },
			{ degree: "MD (Cardiology)", institution: "NICVD", passingYear: 2015 },
		],
		designation: "Consultant",
		experience: 21,
		bio: "Multidisciplinary specialist in Medicine, Diabetes & Cardiology at NICVD.",
		contact: { phone: "+88 09610010615", email: "sufia.jannat@ibnsina.com" },
		gender: "female",
		bmdc: "BMDC-IS-006",
		speciality: ["Medicine", "Diabetes", "Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 155,
	},
	{
		name: "Prof. Dr. Md. Monsurul Haque",
		slug: "prof-dr-md-monsurul-haque",
		departments: ["Cardiology", "Interventional Cardiology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1989 },
			{ degree: "MD (Cardiology)", institution: "NICVD", passingYear: 1999 },
			{ degree: "USMLE (USA)", institution: "USA", passingYear: 2004 },
		],
		designation: "Professor",
		experience: 34,
		bio: "Expert in Clinical & Interventional Cardiology at NICVD with USA certification.",
		contact: { phone: "+88 09610010615", email: "monsurul.haque@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-007",
		speciality: ["Clinical Cardiology", "Interventional Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 190,
	},
	{
		name: "Prof. Dr. M. Touhidul Haque",
		slug: "prof-dr-m-touhidul-haque",
		departments: ["Cardiology", "Interventional Cardiology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1986 },
			{ degree: "MD(Cardiology)", institution: "", passingYear: 1996 },
			{ degree: "FACC(America)", institution: "USA", passingYear: 2005 },
		],
		designation: "Professor",
		experience: 37,
		bio: "Professor at Bangladesh Medical College and WHO Fellow.",
		contact: { phone: "+88 09610010615", email: "touhidul.haque@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-008",
		speciality: ["Clinical & Interventional Cardiology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.7,
		reviewCount: 145,
	},
	{
		name: "Prof. Dr. Mohsin Ahmed",
		slug: "prof-dr-mohsin-ahmed",
		departments: ["Cardiology", "Internal Medicine"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1992 },
			{ degree: "MD", institution: "NICVD", passingYear: 2002 },
			{ degree: "FACC", institution: "USA", passingYear: 2010 },
		],
		designation: "Professor",
		experience: 31,
		bio: "Professor of Cardiology & Medicine at NICVD.",
		contact: { phone: "+88 09610010615", email: "mohsin.ahmed@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-009",
		speciality: ["Cardiology", "Medicine"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 230,
	},
	{
		name: "Professor Dr. M. Delwar Hossain",
		slug: "professor-dr-m-delwar-hossain",
		departments: ["Pulmonology", "Internal Medicine"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1984 },
			{ degree: "DTCD", institution: "", passingYear: 1990 },
			{ degree: "MD (Chest)", institution: "NIDCH", passingYear: 1997 },
		],
		designation: "Professor & Director",
		experience: 39,
		bio: "Expert Pulmonologist and former Director of NIDCH.",
		contact: { phone: "+88 09610010615", email: "delwar.hossain@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-010",
		speciality: ["Pulmonology", "Chest Medicine"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.9,
		reviewCount: 380,
	},
	{
		name: "Professor. Dr.A.K.M. Rafiqul Bari",
		slug: "professor-dr-a-k-m-rafiqul-bari",
		departments: ["Pulmonology", "Allergy and Immunology", "Internal Medicine"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1986 },
			{ degree: "MD (Chest)", institution: "NIDCH", passingYear: 1995 },
			{ degree: "FCCP (USA)", institution: "USA", passingYear: 2002 },
		],
		designation: "Professor & Head",
		experience: 37,
		bio: "Head of Respiratory Medicine at National Chest Diseases Institute.",
		contact: { phone: "+88 09610010615", email: "rafiqul.bari@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-011",
		speciality: ["Asthma", "Chest Disease", "Allergy"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.7,
		reviewCount: 205,
	},
	{
		name: "Dr. Talibul Islam (Rusho)",
		slug: "dr-talibul-islam-rusho",
		departments: ["Pulmonology", "Sleep Medicine"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 2005 },
			{ degree: "MD(Chest Medicine)", institution: "BSMMU", passingYear: 2014 },
		],
		designation: "Asst. Professor",
		experience: 18,
		bio: "Specialist in Chest, Respiratory & Sleep Medicine at TB Hospital Shyamoli.",
		contact: { phone: "+88 09610010615", email: "talibul.islam@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-012",
		speciality: ["Sleep Medicine", "Respiratory Care"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.6,
		reviewCount: 95,
	},
	{
		name: "Professor Dr. Jhunu Shamsun Nahar",
		slug: "professor-dr-jhunu-shamsun-nahar",
		departments: ["Psychiatry"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1982 },
			{ degree: "FCPS (Psych)", institution: "BCPS", passingYear: 1990 },
		],
		designation: "Professor & Ex. Chairman",
		experience: 41,
		bio: "Former Chairman of Psychiatry at BSMMU, expert in Psychotherapy.",
		contact: { phone: "+88 09610010615", email: "jhunu.nahar@ibnsina.com" },
		gender: "female",
		bmdc: "BMDC-IS-013",
		speciality: ["Psychiatry", "Psychotherapy"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.9,
		reviewCount: 420,
	},
	{
		name: "Prof. Dr. AHM Mustafizur Rahman",
		slug: "prof-dr-ahm-mustafizur-rahman",
		departments: ["Psychiatry"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1985 },
			{ degree: "FCPS (Psych)", institution: "BCPS", passingYear: 1993 },
		],
		designation: "Professor",
		experience: 38,
		bio: "Professor at NIMH (Ex.) specializing in Psychiatry and Psychotherapy.",
		contact: { phone: "+88 09610010615", email: "mustafizur.rahman@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-014",
		speciality: ["Mental Health", "Psychotherapy"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 310,
	},
	{
		name: "Prof. Dr. AKM Fazlul Hoque",
		slug: "prof-dr-akm-fazlul-hoque",
		departments: ["General Surgery"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1980 },
			{ degree: "FCPS", institution: "BCPS", passingYear: 1987 },
			{ degree: "FICS", institution: "", passingYear: 1992 },
		],
		designation: "Professor & Founder Chairman",
		experience: 43,
		bio: "Founder Chairman of Colorectal Surgery at BSMMU. Renowned Colorectal Surgeon.",
		contact: { phone: "+88 09610010615", email: "fazlul.hoque@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-015",
		speciality: ["Colorectal Surgery", "Piles", "Fistula"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 5.0,
		reviewCount: 650,
	},
	{
		name: "Brig. Gen. (Retd.) Prof. Dr. Md. Saidur Rahman",
		slug: "brig-gen-retd-prof-dr-md-saidur-rahman",
		departments: ["General Surgery"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1983 },
			{ degree: "FCPS (Surgery)", institution: "BCPS", passingYear: 1991 },
			{ degree: "FICS (USA)", institution: "USA", passingYear: 1998 },
		],
		designation: "Professor & Head",
		experience: 40,
		bio: "Head of Surgery at Anwer Khan Modern Medical College and Hospital.",
		contact: { phone: "+88 09610010615", email: "saidur.rahman@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-016",
		speciality: ["Laparoscopic Surgery", "Colorectal Surgery"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.7,
		reviewCount: 180,
	},
	{
		name: "Prof. Dr. Md. Sanawar Hossain",
		slug: "prof-dr-md-sanawar-hossain",
		departments: ["General Surgery", "Oncology"],
		qualifications: [
			{ degree: "MBBS", institution: "", passingYear: 1991 },
			{ degree: "FCPS (Surgery)", institution: "BCPS", passingYear: 1999 },
			{ degree: "FICS", institution: "", passingYear: 2005 },
		],
		designation: "Professor",
		experience: 32,
		bio: "Professor at BSMMU specializing in General, Breast, and Cancer Surgery.",
		contact: { phone: "+88 09610010615", email: "sanawar.hossain@ibnsina.com" },
		gender: "male",
		bmdc: "BMDC-IS-017",
		speciality: ["Laparoscopic Surgery", "Breast Surgery", "Surgical Oncology"],
		chamber: [IBN_SINA_DHANMONDI_ID],
		isVerified: true,
		isActive: true,
		rating: 4.8,
		reviewCount: 210,
	},
];

async function seedDoctors() {
	try {
		await mongoose.connect(
			"mongodb+srv://meherajhosen786_db_user:hossen5799raj@primary.ydl4rgk.mongodb.net/dhaka-aggregator"
		);
		console.log("✅ MongoDB Connected");

		let insertedCount = 0;

		for (const doc of doctorsSeed) {
			const existing = await Doctor.findOne({ bmdc: doc.bmdc });
			if (existing) {
				console.log(`⚠️ Already exists: ${doc.name}`);
				continue;
			}

			await Doctor.create(doc);
			insertedCount++;
			console.log(`✅ Added: ${doc.name}`);
		}

		console.log(`🎉 Successfully seeded ${insertedCount} doctors!`);
	} catch (error: any) {
		console.error("❌ Seeding failed:", error.message);
	} finally {
		await mongoose.disconnect();
	}
}

seedDoctors();